using System.Collections.Generic;
using UnityEngine;

public class IncantationWordLibrary : MonoBehaviour
{
    [Header("Incantation Vocabulary")]
    [Tooltip("Single source of truth for generated incantation words and their speech recognition aliases.")]
    [SerializeField] private List<IncantationWord> words = new List<IncantationWord>
    {
        new IncantationWord("ordo", new[] { "or do" }),
        new IncantationWord("tenebris", new[] { "deliveries" }),
        new IncantationWord("maledictum", new[] { "malediction" }),
        new IncantationWord("umbra", new[] { "umbrella" }),
        new IncantationWord("vinculum", new[] { "vehicle um" }),
        new IncantationWord("abyssus", new[] { "abyss us" }),
        new IncantationWord("acerbus"),
        new IncantationWord("adumbratus"),
        new IncantationWord("aeternum"),
        new IncantationWord("altarium"),
        new IncantationWord("amissus"),
        new IncantationWord("animae"),
        new IncantationWord("animarum"),
        new IncantationWord("arcana"),
        new IncantationWord("arcanum"),
        new IncantationWord("ardens"),
        new IncantationWord("astralis"),
        new IncantationWord("ater"),
        new IncantationWord("atramentum"),
        new IncantationWord("augurium"),
        new IncantationWord("bellator"),
        new IncantationWord("caecitas"),
        new IncantationWord("caligo", new[] { "cali go" }),
        new IncantationWord("cantus"),
        new IncantationWord("carceris"),
        new IncantationWord("carnifex"),
        new IncantationWord("cineris"),
        new IncantationWord("circulus"),
        new IncantationWord("clamor"),
        new IncantationWord("clavicula"),
        new IncantationWord("corvus"),
        new IncantationWord("cruciatus"),
        new IncantationWord("custos"),
        new IncantationWord("daemonium"),
        new IncantationWord("damnatio"),
        new IncantationWord("decretum"),
        new IncantationWord("delirium"),
        new IncantationWord("devorator"),
        new IncantationWord("diabolus"),
        new IncantationWord("dirum"),
        new IncantationWord("dolorum"),
        new IncantationWord("draconis"),
        new IncantationWord("effigies"),
        new IncantationWord("exanimis"),
        new IncantationWord("excidium"),
        new IncantationWord("exsanguis"),
        new IncantationWord("fatum"),
        new IncantationWord("feralis"),
        new IncantationWord("ferox"),
        new IncantationWord("funestus"),
        new IncantationWord("furor"),
        new IncantationWord("gelidus"),
        new IncantationWord("geminus"),
        new IncantationWord("gladius"),
        new IncantationWord("gravis"),
        new IncantationWord("horrendum"),
        new IncantationWord("hostilis"),
        new IncantationWord("immortalis"),
        new IncantationWord("imperium"),
        new IncantationWord("infernum"),
        new IncantationWord("infernus"),
        new IncantationWord("invidia"),
        new IncantationWord("invocatio"),
        new IncantationWord("iudicium"),
        new IncantationWord("lacrimae"),
        new IncantationWord("lamentum"),
        new IncantationWord("larvae"),
        new IncantationWord("lemures"),
        new IncantationWord("letalis"),
        new IncantationWord("ligatura"),
        new IncantationWord("luctuosus"),
        new IncantationWord("lunaris"),
        new IncantationWord("macula"),
        new IncantationWord("manium"),
        new IncantationWord("mors"),
        new IncantationWord("mortifer"),
        new IncantationWord("mortuus"),
        new IncantationWord("mysterium"),
        new IncantationWord("necromantia", new[] { "necromancy" }),
        new IncantationWord("nex"),
        new IncantationWord("nocturnus"),
        new IncantationWord("nomen"),
        new IncantationWord("obscurum", new[] { "obscure room" }),
        new IncantationWord("obscurus", new[] { "obscure us" }),
        new IncantationWord("occultum"),
        new IncantationWord("omen"),
        new IncantationWord("opprobrium"),
        new IncantationWord("oraculum"),
        new IncantationWord("pallidus"),
        new IncantationWord("penumbra"),
        new IncantationWord("perditus"),
        new IncantationWord("periculum"),
        new IncantationWord("phantasma", new[] { "phantom" }),
        new IncantationWord("portentum"),
        new IncantationWord("praesagium"),
        new IncantationWord("profanum"),
        new IncantationWord("purgatorium"),
        new IncantationWord("quietus"),
        new IncantationWord("raptus"),
        new IncantationWord("reliquiae"),
        new IncantationWord("ruina"),
        new IncantationWord("sacrilegium"),
        new IncantationWord("sanguinis", new[] { "sanguineous" }),
        new IncantationWord("sepulcrum", new[] { "sepulcher" }),
        new IncantationWord("serpentis"),
        new IncantationWord("silentium"),
        new IncantationWord("simulacrum")
    };

    public IReadOnlyList<IncantationWord> Words
    {
        get
        {
            if (words == null)
                words = new List<IncantationWord>();

            return words;
        }
    }
}
